#!/usr/bin/env bash
# scripts/test/run-fuzz-restore.sh
#
# Fuzz the backup-state restore parser. restoreCalc() reads backup.cfg - the
# persisted calculator state loaded on every boot - into a parameter list and
# extracts every field by key and type. A corrupt backup.cfg is untrusted input,
# which makes the restore parser a high-yield robustness target.
#
# It overlays the libFuzzer harness (scripts/test/tooling/fuzz-restore.patch,
# carried off the test/fuzz-restore-harness branch off upstream master), builds
# the fuzzRestore target and the native genBackup seed maker under clang with
# -fsanitize=fuzzer,address,undefined (ASan crash gate; UBSan report mode; the
# alignment check is off because the calculator packs data unaligned by design),
# generates a valid backup.cfg seed, and runs a time-boxed campaign.
#
# Report-first: a crash is surfaced and its reproducer uploaded, but the lane
# only fails when FUZZ_GATE=1. Env knobs: FUZZ_TIME (seconds, default 60),
# FUZZ_MAXLEN (bytes), FUZZ_GATE (1 to fail on a finding), BUILD_DIR.

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/common.sh
. "$SCRIPT_DIR/lib/common.sh"

TOOLING_PATCH="${TOOLING_PATCH:-$SCRIPT_DIR/tooling/fuzz-restore.patch}"
# The seed (a valid backup.cfg) is generated by the native genBackup helper, not
# carried in the repo - it is ~1 MB of state and would drift with the format.
DICT="${DICT:-$SCRIPT_DIR/tooling/fuzz-restore.dict}"
BUILD_DIR="${BUILD_DIR:-build.fuzzrs}"
FUZZ_TIME="${FUZZ_TIME:-60}"
FUZZ_MAXLEN="${FUZZ_MAXLEN:-4096}"
FUZZ_GATE="${FUZZ_GATE:-0}"

main() {
    harness_init
    command -v clang > /dev/null || harness_die "clang required for libFuzzer (apt-get install clang)"

    local commit
    commit="$(harness_resolve_commit)"
    harness_log "fuzzing restoreCalc against upstream $commit"
    harness_sync_upstream "$commit"

    [[ -f "$TOOLING_PATCH" ]] || harness_die "tooling patch not found: $TOOLING_PATCH"
    if ! git -C "$UPSTREAM_DIR" apply --check "$TOOLING_PATCH" 2> /dev/null; then
        harness_die "fuzz-restore.patch does not apply on upstream $commit; rebase the
        test/fuzz-restore-harness tooling onto current upstream and regenerate
        scripts/test/tooling/fuzz-restore.patch"
    fi
    git -C "$UPSTREAM_DIR" apply "$TOOLING_PATCH"
    harness_log "overlaid libFuzzer harness"

    harness_setup_xlsxio

    harness_log "building fuzzRestore under clang ($BUILD_DIR)"
    (
        cd "$UPSTREAM_DIR"
        chmod +x tools/onARaspberry
        local raspberry
        raspberry="$(./tools/onARaspberry)"
        rm -rf "$BUILD_DIR"
        CC=clang CXX=clang++ meson setup "$BUILD_DIR" --buildtype=custom \
            -DRASPBERRY="$raspberry" -DDECNUMBER_FASTMUL=true \
            -Dfuzz_restore=true \
            -Dc_args="-Wno-deprecated-declarations" > "$LOG_DIR/fuzz-build.log" 2>&1
        ninja -C "$BUILD_DIR" src/c47/vcs.h >> "$LOG_DIR/fuzz-build.log" 2>&1
        # fuzzRestore is the libFuzzer harness; genBackup is the native seed maker.
        ninja -C "$BUILD_DIR" "-j$(harness_jobs)" src/testSuite/fuzzRestore src/testSuite/genBackup >> "$LOG_DIR/fuzz-build.log" 2>&1
    ) || harness_die "fuzz build failed (see $LOG_DIR/fuzz-build.log)"

    local bin="$UPSTREAM_DIR/$BUILD_DIR/src/testSuite/fuzzRestore"
    [[ -x "$bin" ]] || harness_die "fuzzRestore binary not built"
    local gen="$UPSTREAM_DIR/$BUILD_DIR/src/testSuite/genBackup"
    [[ -x "$gen" ]] || harness_die "genBackup seed generator not built"

    # Run from a scratch dir; generate the seed corpus with genBackup, which writes
    # a structurally valid backupTest.cfg so mutations start from a parseable file
    # and reach the deeper field parsers instead of failing the version/ramSize
    # checks. The testSuite HAL suffixes every writable path with "Test"
    # (ioPathBackup -> backupTest.cfg), so the seed and the harness both use that
    # name; restoreCalc() opens the same path through the HAL.
    local run_dir="$HARNESS_WORK/run"
    rm -rf "$run_dir"
    mkdir -p "$run_dir/corpus"
    (cd "$run_dir/corpus" && "$gen") > "$LOG_DIR/fuzz-seed-gen.log" 2>&1 || true
    [[ -s "$run_dir/corpus/backupTest.cfg" ]] || harness_die "genBackup did not produce a seed backupTest.cfg"

    local dict_arg=()
    [[ -f "$DICT" ]] && dict_arg=("-dict=$DICT")

    harness_log "running a ${FUZZ_TIME}s campaign (max_len=$FUZZ_MAXLEN, ASan/UBSan)"
    local rc=0
    (
        cd "$run_dir"
        export UBSAN_OPTIONS="halt_on_error=0:print_stacktrace=1"
        # restoreCalc() reloads and churns persistent calculator state each input, so
        # per-input leak detection is not meaningful here (and it carries a known,
        # minor glyphNotFound one-shot leak): gate on ASan memory errors, not leaks.
        export ASAN_OPTIONS="detect_leaks=0:abort_on_error=0"
        "$bin" -max_total_time="$FUZZ_TIME" -max_len="$FUZZ_MAXLEN" \
            -rss_limit_mb=4096 -artifact_prefix="$LOG_DIR/fuzz-" \
            "${dict_arg[@]}" corpus/
    ) > "$LOG_DIR/fuzz-campaign.log" 2>&1 || rc=$?

    # Preserve the evolved corpus for the next run / OSS-Fuzz seeding.
    tar -czf "$LOG_DIR/fuzz-corpus.tar.gz" -C "$run_dir" corpus 2> /dev/null || true

    local crashes
    crashes="$(ls "$LOG_DIR"/fuzz-crash-* "$LOG_DIR"/fuzz-leak-* "$LOG_DIR"/fuzz-oom-* 2> /dev/null || true)"
    if [[ -n "$crashes" ]]; then
        harness_log "FUZZ FINDING(s) - reproducers saved (re-run: fuzzRestore <file>):"
        printf ' %s\n' $crashes
        # Surface the sanitizer summary lines for triage.
        grep -E "ERROR: AddressSanitizer|SUMMARY: (AddressSanitizer|UndefinedBehaviorSanitizer)|in [a-zA-Z_]+ /" \
            "$LOG_DIR/fuzz-campaign.log" | head -8 | sed 's/^/ /' || true
        if [[ "$FUZZ_GATE" == "1" ]]; then
            harness_die "fuzz gate failed: $(printf '%s\n' $crashes | grep -c .) finding(s)"
        fi
        harness_log "report-first: not failing the lane (set FUZZ_GATE=1 to gate)"
        return 0
    fi

    harness_log "campaign finished with no ASan finding (rc=$rc); corpus saved to fuzz-corpus.tar.gz"
}

main "$@"
